#!/usr/bin/env python3
"""GF-010 deterministic A-T acceptance using isolated local Git remotes."""

from __future__ import annotations
import argparse, hashlib, json, os, pathlib, shutil, subprocess, tempfile, time

ROOT = pathlib.Path(__file__).resolve().parents[2]
CLI = ROOT / "scripts/gf-approve.sh"
CANDIDATE_IDENTITY_VERSION = 2
NAMES = {
 "A":"approval_required", "B":"approved_direct_integration", "C":"no_repeated_approval", "D":"candidate_changed",
 "E":"remote_advances_cleanly", "F":"remote_conflict", "G":"crash_after_push", "H":"push_failure_before_remote",
 "I":"ambiguous_push_reconcile", "J":"adoption_clean", "K":"adoption_unrelated", "L":"approval_bundle",
 "M":"multiple_pending", "N":"already_integrated", "O":"pr_policy", "P":"external_reviewer_policy",
 "Q":"post_integration_validation_failure", "R":"cleanup", "S":"scheduler_cannot_approve", "T":"force_push_forbidden",
 "U":"git_stable_candidate_identity"}

def run(args, cwd, env=None, check=True):
    merged=os.environ.copy(); merged.update(env or {})
    result=subprocess.run(args,cwd=cwd,env=merged,text=True,capture_output=True)
    if check and result.returncode: raise RuntimeError(f"{args}: {result.stderr}")
    return result

def git(repo,*args,check=True): return run(["git",*args],repo,check=check).stdout.strip()

def adoption_fingerprint(repo, paths, base):
    identities={}
    for relative in sorted(paths):
        target=repo/relative
        if not target.exists(): identities[relative]="absent"; continue
        mode="100755" if target.stat().st_mode & 0o100 else "100644"
        identities[relative]=f"file:{mode}:{hashlib.sha256(target.read_bytes()).hexdigest()}"
    return hashlib.sha256(json.dumps({"candidate_identity_version":CANDIDATE_IDENTITY_VERSION,"base_sha":base,"paths":identities},sort_keys=True,separators=(",",":")).encode()).hexdigest()

def fixture(root, name, adoption=False, units=1, mode="direct", external=False, validator_body=None, with_milestone_gates=False, shared_dependencies=False, adapter="fixture", evidence_in_adoption=False):
    case=root/name; remote=case/"remote.git"; repo=case/"repo"; state=case/"state"; artifacts=case/"artifacts"
    case.mkdir(parents=True); run(["git","init","--bare","-q",str(remote)],case)
    run(["git","init","-q","-b","main",str(repo)],case)
    git(repo,"config","user.name","GF-010 Test"); git(repo,"config","user.email","gf010@test.invalid")
    if shared_dependencies:
        validator_body="#!/usr/bin/env bash\nset -e\ntest -L node_modules\ntest \"$(cat node_modules/fake-tool.txt)\" = fixture-tool\n"
        (repo/".gitignore").write_text("node_modules/\n"); (repo/"package.json").write_text('{"name":"fixture","private":true}\n'); (repo/"package-lock.json").write_text('{"name":"fixture","lockfileVersion":3}\n'); (repo/"node_modules").mkdir(); (repo/"node_modules/fake-tool.txt").write_text("fixture-tool\n")
    (repo/"validate.sh").write_text(validator_body or "#!/usr/bin/env bash\nset -e\ntest -f feature-0.txt\n",encoding="utf-8"); (repo/"validate.sh").chmod(0o755)
    (repo/"base.txt").write_text("base\n",encoding="utf-8"); git(repo,"add","."); git(repo,"commit","-q","-m","base"); base=git(repo,"rev-parse","HEAD")
    git(repo,"remote","add","origin",str(remote)); git(repo,"push","-q","-u","origin","main")
    evidence=[]
    for index in range(units):
        path=(repo if evidence_in_adoption else case)/f"evidence-{index}.json"; path.write_text(json.dumps({"status":"pass"})+"\n"); evidence.append(path)
    candidate=[]; groups=[]
    if adoption:
        (repo/"feature-0.txt").write_text("approved feature 0\n",encoding="utf-8")
        adoption_paths=["feature-0.txt"]+[f"evidence-{index}.json" for index in range(units) if evidence_in_adoption]
        groups=[{"id":"UNIT","unit_ids":[f"UNIT-{i}" for i in range(units)],"commit_message":"adopt feature","paths":adoption_paths}]
    else:
        for index in range(units):
            relative=f"feature-{index}.txt"; (repo/relative).write_text(f"approved feature {index}\n",encoding="utf-8")
            git(repo,"add",relative); git(repo,"commit","-q","-m",f"candidate {index}"); sha=git(repo,"rev-parse","HEAD"); tree=git(repo,"rev-parse","HEAD^{tree}"); candidate.append({"sha":sha,"tree_sha":tree,"unit_ids":[f"UNIT-{index}"],"paths":[relative]})
        git(repo,"reset","-q","--hard",base)
    for index,path in enumerate(evidence):
        value={"status":"pass","unit_id":f"UNIT-{index}"}
        if not adoption: value["candidate_sha"]=candidate[index]["sha"]
        path.write_text(json.dumps(value,sort_keys=True)+"\n",encoding="utf-8")
    integration={"mode":mode,"allow_force_push":False,"verify_remote":True}
    policy_integration={"repository":str(repo),"manifest_roots":[str(case)],"allow_untracked_manifests_for_fixtures":True,"remote":"origin","remote_url":str(remote),"push_url":str(remote),"target_branch":"main",**integration,"validation_commands":[["./validate.sh"]]}
    if shared_dependencies: policy_integration["validation_dependency_mode"]="shared_locked_node_modules"
    if mode=="pull_request":
        integration.update({"pr_adapter":adapter,"external_reviewer_required":external,"merge_method":"merge","required_checks":True,"require_strict_base_checks":True})
        policy_integration.update({"pr_adapter":adapter,"external_reviewer_required":external,"merge_method":"merge","required_checks":True,"require_strict_base_checks":True})
        if adapter=="github": integration["github_repository"]="fixture/repo"; policy_integration["github_repository"]="fixture/repo"
    policy=case/"integration-policy.json"; policy.write_text(json.dumps({"schema_version":1,"repositories":{"fixture":policy_integration}},indent=2)+"\n")
    manifest={"schema_version":1,"approval_id":name,"approval_type":"adoption_bundle" if adoption else "candidate_bundle","project_id":"fixture","repository":str(repo),"base_sha":base,"units":[{"id":f"UNIT-{i}","validation_evidence":str(evidence[i]),"critic_required":False} for i in range(units)],"evidence_bindings":[{"unit_id":f"UNIT-{i}","validation_sha256":hashlib.sha256(evidence[i].read_bytes()).hexdigest()} for i in range(units)],"remote":"origin","target_branch":"main","integration":integration,"validation_commands":[["./validate.sh"]]}
    if adoption:
        manifest["adoption"]={"groups":groups}; manifest["candidate_identity_version"]=CANDIDATE_IDENTITY_VERSION; manifest["candidate_patch_sha256"]=adoption_fingerprint(repo,groups[0]["paths"],base)
    else: manifest["candidate_commits"]=candidate
    milestone_state=case/"milestones"
    if with_milestone_gates:
        manifest["milestone_gates"]=[]
        for index in range(units):
            milestone_id=f"GF-FIXTURE-{name.upper()}-{index}"; package=case/"milestone-packages"/milestone_id; (package/"tasks").mkdir(parents=True)
            (package/"design.md").write_text("# Fixture design\n"); (package/"guidelines.md").write_text("# Fixture guidelines\n")
            milestone_value={"id":milestone_id,"title":f"Fixture {index}","version":1,"repository":{"name":"fixture","path":str(repo)},"design":"design.md","guidelines":"guidelines.md","tasks":[f"tasks/UNIT-{index}.json"],"completion_gate":"human_review"}
            task_value={"id":f"UNIT-{index}","title":f"Unit {index}","objective":"Exercise approval gate","depends_on":[],"allowed_scope":[f"feature-{index}.txt"],"acceptance":["fixture passes"],"retry_policy":{"max_attempts":1},"on_failure":"escalate"}
            (package/"milestone.json").write_text(json.dumps(milestone_value,indent=2)+"\n"); (package/f"tasks/UNIT-{index}.json").write_text(json.dumps(task_value,indent=2)+"\n")
            milestone_env={"GF_MILESTONE_STATE_ROOT":str(milestone_state)}
            run([str(ROOT/"scripts/gf-milestone.sh"),"init",str(package)],case,env=milestone_env)
            run([str(ROOT/"scripts/gf-milestone.sh"),"transition",milestone_id,f"UNIT-{index}","running"],case,env=milestone_env)
            run([str(ROOT/"scripts/gf-milestone.sh"),"transition",milestone_id,f"UNIT-{index}","pass"],case,env=milestone_env)
            manifest["milestone_gates"].append({"milestone_id":milestone_id,"task_ids":[f"UNIT-{index}"]})
    manifest_path=case/"manifest.json"; manifest_path.write_text(json.dumps(manifest,indent=2)+"\n")
    env={"GF_APPROVAL_STATE_ROOT":str(state),"GF_APPROVAL_ARTIFACT_ROOT":str(artifacts),"GF_APPROVAL_POLICY_CONFIG":str(policy),"GF_MILESTONE_STATE_ROOT":str(milestone_state)}
    return case,repo,remote,manifest_path,env,base

def cli(case, env, *args, check=True, fault=None, extra_env=None):
    use=dict(env)
    if fault: use.update({"GF_GF010_ENABLE_TEST_HOOKS":"1","GF_GF010_FAULT":fault})
    use.update(extra_env or {})
    return run([str(CLI),*args],case,env=use,check=check)

def record(results, letter, passed, detail=""):
    results.append({"test":letter,"name":NAMES[letter],"status":"pass" if passed else "fail","detail":detail or None})

def iteration(root, number, evidence_root=None):
    results=[]
    # A/B/C/N/R share a successful direct transaction.
    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-direct")
    cli(case,env,"create",str(manifest)); before=git(repo,"rev-parse","refs/remotes/origin/main")
    blocked=cli(case,env,"integrate",f"i{number}-direct",check=False); after=git(repo,"rev-parse","refs/remotes/origin/main")
    record(results,"A",blocked.returncode!=0 and before==after)
    approved=cli(case,env,"approve",f"i{number}-direct","--source","operator_agent_explicit_human")
    state=json.loads((pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-direct.json").read_text())
    direct_receipt_path=pathlib.Path(env["GF_APPROVAL_ARTIFACT_ROOT"])/f"i{number}-direct"/"result.json"; direct_receipt_value=json.loads(direct_receipt_path.read_text()) if direct_receipt_path.is_file() else {}; receipt_fields={"approval_id","status","candidates","base","remote_head_before","integration_head","integration_method","pr_number","merge_commit","validation","push","remote_verification","cleanup","remote_head_after","duration_seconds","human_action_required","failure_class","failure_reason"}; direct_receipt=receipt_fields.issubset(direct_receipt_value) and direct_receipt_value.get("status")=="INTEGRATED" and direct_receipt_value.get("validation",{}).get("status")=="pass" and direct_receipt_value.get("remote_verification",{}).get("status")=="pass" and direct_receipt_value.get("duration_seconds") is not None
    record(results,"B",approved.returncode==0 and state["integration_status"]=="INTEGRATED" and state["remote_head_after"]==state["integration_commit"])
    record(results,"C",state["approval_status"]=="integrated" and not state["human_action_required"])
    head=git(repo,"ls-remote","origin","refs/heads/main").split()[0]; again=cli(case,env,"integrate",f"i{number}-direct"); head2=git(repo,"ls-remote","origin","refs/heads/main").split()[0]; record_before_reconcile=(pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-direct.json").read_bytes()
    other=case/"post-integration-advance"; run(["git","clone","-q",str(remote),str(other)],case); git(other,"checkout","-q","-b","main","origin/main"); git(other,"config","user.name","Remote"); git(other,"config","user.email","remote@test"); (other/"later.txt").write_text("later normal advance\n"); git(other,"add","."); git(other,"commit","-q","-m","later advance"); git(other,"push","-q","origin","main"); advanced_head=git(repo,"ls-remote","origin","refs/heads/main").split()[0]; reconciled_integrated=cli(case,env,"reconcile",f"i{number}-direct"); record_after_reconcile=(pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-direct.json").read_bytes()
    record(results,"N",again.returncode==0 and reconciled_integrated.returncode==0 and head==head2 and advanced_head!=head and record_before_reconcile==record_after_reconcile)
    record(results,"R",state.get("cleanup",{}).get("temporary_worktree_removed") is True)

    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-changed",adoption=True); cli(case,env,"create",str(manifest)); (repo/"feature-0.txt").write_text("changed after bundle\n")
    changed=cli(case,env,"approve",f"i{number}-changed","--source","operator_agent_explicit_human",check=False)
    case2,repo2,remote2,manifest2,env2,base2=fixture(root,f"i{number}-evidence-changed"); cli(case2,env2,"create",str(manifest2)); (case2/"evidence-0.json").write_text(json.dumps({"status":"pass","changed":True})+"\n"); evidence_changed=cli(case2,env2,"approve",f"i{number}-evidence-changed","--source","operator_agent_explicit_human",check=False)
    record(results,"D",changed.returncode!=0 and "CANDIDATE_CHANGED" in changed.stderr and evidence_changed.returncode!=0 and "EVIDENCE_CHANGED" in evidence_changed.stderr)

    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-advance"); cli(case,env,"create",str(manifest))
    other=case/"other"; run(["git","clone","-q",str(remote),str(other)],case); git(other,"checkout","-q","-b","main","origin/main"); git(other,"config","user.name","Remote"); git(other,"config","user.email","remote@test"); (other/"remote.txt").write_text("advance\n"); git(other,"add","."); git(other,"commit","-q","-m","advance"); git(other,"push","-q","origin","main")
    advanced=cli(case,env,"approve",f"i{number}-advance","--source","operator_agent_explicit_human"); record(results,"E",advanced.returncode==0 and (other/"remote.txt").exists())
    resetting_validator="#!/usr/bin/env bash\nset -e\ntest -f feature-0.txt\ngit push --force origin \"$GF_TEST_RESET_SHA:refs/heads/main\" >/dev/null 2>&1\n"
    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-reset-before-push",validator_body=resetting_validator); cli(case,env,"create",str(manifest)); other=case/"other"; run(["git","clone","-q",str(remote),str(other)],case); git(other,"checkout","-q","-b","main","origin/main"); git(other,"config","user.name","Remote"); git(other,"config","user.email","remote@test"); (other/"new-base.txt").write_text("base B\n"); git(other,"add","."); git(other,"commit","-q","-m","base B"); git(other,"push","-q","origin","main"); reset_attempt=cli(case,env,"approve",f"i{number}-reset-before-push","--source","operator_agent_explicit_human",check=False,extra_env={"GF_TEST_RESET_SHA":base}); reset_state=json.loads((pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-reset-before-push.json").read_text()); e_result=results[-1]; reset_safe=reset_attempt.returncode!=0 and reset_state["failure_class"]=="REMOTE_REWRITTEN_BEFORE_PUSH" and git(repo,"ls-remote","origin","refs/heads/main").split()[0]==base; e_result["status"]="pass" if e_result["status"]=="pass" and reset_safe else "fail"; e_result["detail"]=None if e_result["status"]=="pass" else "clean advance or reset-before-push handling failed"

    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-conflict"); cli(case,env,"create",str(manifest)); other=case/"other"; run(["git","clone","-q",str(remote),str(other)],case); git(other,"checkout","-q","-b","main","origin/main"); git(other,"config","user.name","Remote"); git(other,"config","user.email","remote@test"); (other/"feature-0.txt").write_text("remote conflict\n"); git(other,"add","."); git(other,"commit","-q","-m","conflict"); git(other,"push","-q","origin","main")
    conflict=cli(case,env,"approve",f"i{number}-conflict","--source","operator_agent_explicit_human",check=False); record(results,"F",conflict.returncode!=0 and "INTEGRATION_CONFLICT" in conflict.stderr)

    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-crash"); cli(case,env,"create",str(manifest)); crashed=cli(case,env,"approve",f"i{number}-crash","--source","operator_agent_explicit_human",check=False,fault="crash_after_push"); crash_state_path=pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-crash.json"; pre_reconcile=json.loads(crash_state_path.read_text()); orphan=pathlib.Path(pre_reconcile["worktree_path"]); reconciled=cli(case,env,"reconcile",f"i{number}-crash"); state=json.loads(crash_state_path.read_text()); crash_receipt=(pathlib.Path(env["GF_APPROVAL_ARTIFACT_ROOT"])/f"i{number}-crash"/"result.json").is_file(); crash_cleanup=orphan.exists() is False and state.get("cleanup",{}).get("temporary_worktree_removed") is True; record(results,"G",crashed.returncode==97 and crash_cleanup and crash_receipt and reconciled.returncode==0 and state["integration_status"]=="INTEGRATED")
    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-crash-evidence-missing"); cli(case,env,"create",str(manifest)); evidence_crash=cli(case,env,"approve",f"i{number}-crash-evidence-missing","--source","operator_agent_explicit_human",check=False,fault="crash_after_push"); evidence_state_path=pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-crash-evidence-missing.json"; evidence_before=json.loads(evidence_state_path.read_text()); pathlib.Path(evidence_before["evidence_snapshots"][0]["validation_path"]).unlink(); evidence_reconcile=cli(case,env,"reconcile",f"i{number}-crash-evidence-missing",check=False); evidence_after=json.loads(evidence_state_path.read_text()); evidence_recovery_safe=evidence_crash.returncode==97 and evidence_reconcile.returncode!=0 and evidence_after["failure_class"]=="EVIDENCE_CHANGED" and evidence_after["integration_status"]=="HUMAN_REQUIRED" and evidence_after.get("cleanup",{}).get("temporary_worktree_removed") is True
    g_result=results[-1]; g_result["status"]="pass" if g_result["status"]=="pass" and evidence_recovery_safe else "fail"; g_result["detail"]=None if g_result["status"]=="pass" else "crash recovery accepted missing bound evidence or failed cleanup"
    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-crash-prepush"); cli(case,env,"create",str(manifest)); prepush_crash=cli(case,env,"approve",f"i{number}-crash-prepush","--source","operator_agent_explicit_human",check=False,fault="crash_after_worktree_created"); prepush_state_path=pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-crash-prepush.json"; prepush_before=json.loads(prepush_state_path.read_text()); prepush_orphan=pathlib.Path(prepush_before["worktree_path"]); prepush_recovered=cli(case,env,"reconcile",f"i{number}-crash-prepush"); prepush_state=json.loads(prepush_state_path.read_text()); prepush_ok=prepush_crash.returncode==96 and prepush_recovered.returncode==0 and not prepush_orphan.exists() and prepush_state["integration_status"]=="INTEGRATED" and [item["name"] for item in prepush_state["checkpoints"]].count("RECOVERY_CLEANUP_COMPLETE")==1; g_result=next(entry for entry in results if entry["test"]=="G"); g_result["status"]="pass" if g_result["status"]=="pass" and prepush_ok else "fail"; g_result["detail"]=None if g_result["status"]=="pass" else "pre-push or post-push crash recovery failed"
    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-crash-worktree-gap"); cli(case,env,"create",str(manifest)); gap_crash=cli(case,env,"approve",f"i{number}-crash-worktree-gap","--source","operator_agent_explicit_human",check=False,fault="crash_after_worktree_add_before_checkpoint"); gap_state_path=pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-crash-worktree-gap.json"; gap_before=json.loads(gap_state_path.read_text()); gap_path=pathlib.Path(gap_before["worktree_path"]); gap_recovered=cli(case,env,"reconcile",f"i{number}-crash-worktree-gap"); gap_state=json.loads(gap_state_path.read_text()); gap_ok=gap_crash.returncode==94 and gap_recovered.returncode==0 and not gap_path.exists() and gap_state["integration_status"]=="INTEGRATED" and "WORKTREE_PATH_RESERVED" in [item["name"] for item in gap_state["checkpoints"]]; g_result["status"]="pass" if g_result["status"]=="pass" and gap_ok else "fail"; g_result["detail"]=None if g_result["status"]=="pass" else "reserved worktree crash window was not recoverable"
    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-crash-advanced"); cli(case,env,"create",str(manifest)); advanced_crash=cli(case,env,"approve",f"i{number}-crash-advanced","--source","operator_agent_explicit_human",check=False,fault="crash_after_push"); other=case/"other"; run(["git","clone","-q",str(remote),str(other)],case); git(other,"checkout","-q","-b","main","origin/main"); git(other,"config","user.name","Remote"); git(other,"config","user.email","remote@test"); (other/"after-push.txt").write_text("unexpected\n"); git(other,"add","."); git(other,"commit","-q","-m","advance after push"); git(other,"push","-q","origin","main"); advanced_reconcile=cli(case,env,"reconcile",f"i{number}-crash-advanced",check=False); advanced_state=json.loads((pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-crash-advanced.json").read_text()); g_result=next(entry for entry in results if entry["test"]=="G"); remote_exact_ok=advanced_crash.returncode==97 and advanced_reconcile.returncode!=0 and advanced_state["failure_class"]=="REMOTE_MOVED_AFTER_PUSH" and advanced_state.get("cleanup",{}).get("temporary_worktree_removed") is True; g_result["status"]="pass" if g_result["status"]=="pass" and remote_exact_ok else "fail"; g_result["detail"]=None if g_result["status"]=="pass" else "crash recovery or exact remote-head enforcement failed"
    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-crash-rewritten"); cli(case,env,"create",str(manifest)); rewritten_crash=cli(case,env,"approve",f"i{number}-crash-rewritten","--source","operator_agent_explicit_human",check=False,fault="crash_after_push"); other=case/"other"; run(["git","clone","-q",str(remote),str(other)],case); git(other,"checkout","-q","-b","main","origin/main"); git(other,"config","user.name","Remote"); git(other,"config","user.email","remote@test"); git(other,"reset","-q","--hard",base); (other/"rewrite.txt").write_text("non-descendant\n"); git(other,"add","."); git(other,"commit","-q","-m","rewrite remote"); git(other,"push","-q","--force","origin","main"); rewritten=cli(case,env,"reconcile",f"i{number}-crash-rewritten",check=False); rewritten_state=json.loads((pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-crash-rewritten.json").read_text()); rewrite_ok=rewritten_crash.returncode==97 and rewritten.returncode!=0 and rewritten_state["failure_class"]=="REMOTE_MOVED_AFTER_PUSH" and [item["name"] for item in rewritten_state["checkpoints"]].count("PUSH_STARTED")==1; g_result["status"]="pass" if g_result["status"]=="pass" and rewrite_ok else "fail"; g_result["detail"]=None if g_result["status"]=="pass" else "descendant/non-descendant post-push movement was not fail-closed"

    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-ambiguous-arrived"); cli(case,env,"create",str(manifest)); uncertain=cli(case,env,"approve",f"i{number}-ambiguous-arrived","--source","operator_agent_explicit_human",check=False,fault="ambiguous_push_arrived"); arrived=cli(case,env,"reconcile",f"i{number}-ambiguous-arrived"); arrived_state=json.loads((pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-ambiguous-arrived.json").read_text())
    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-ambiguous-absent"); cli(case,env,"create",str(manifest)); absent_first=cli(case,env,"approve",f"i{number}-ambiguous-absent","--source","operator_agent_explicit_human",check=False,fault="ambiguous_push_absent"); absent_retry=cli(case,env,"reconcile",f"i{number}-ambiguous-absent"); absent_state=json.loads((pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-ambiguous-absent.json").read_text())
    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-ambiguous-unresolved"); cli(case,env,"create",str(manifest)); unresolved_first=cli(case,env,"approve",f"i{number}-ambiguous-unresolved","--source","operator_agent_explicit_human",check=False,fault="ambiguous_push_absent"); other=case/"other"; run(["git","clone","-q",str(remote),str(other)],case); git(other,"checkout","-q","-b","main","origin/main"); git(other,"config","user.name","Remote"); git(other,"config","user.email","remote@test"); (other/"uncertain.txt").write_text("movement\n"); git(other,"add","."); git(other,"commit","-q","-m","uncertain movement"); git(other,"push","-q","origin","main"); unresolved=cli(case,env,"reconcile",f"i{number}-ambiguous-unresolved",check=False); unresolved_state=json.loads((pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-ambiguous-unresolved.json").read_text())
    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-ambiguous-evidence-changed"); cli(case,env,"create",str(manifest)); changed_first=cli(case,env,"approve",f"i{number}-ambiguous-evidence-changed","--source","operator_agent_explicit_human",check=False,fault="ambiguous_push_absent"); (case/"evidence-0.json").write_text(json.dumps({"status":"pass","changed":True})+"\n"); changed_reconcile=cli(case,env,"reconcile",f"i{number}-ambiguous-evidence-changed",check=False); changed_state=json.loads((pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-ambiguous-evidence-changed.json").read_text()); changed_remote=git(repo,"ls-remote","origin","refs/heads/main").split()[0]
    record(results,"I",uncertain.returncode==70 and arrived.returncode==0 and arrived_state["integration_status"]=="INTEGRATED" and absent_first.returncode==70 and absent_retry.returncode==0 and absent_state["integration_status"]=="INTEGRATED" and unresolved_first.returncode==70 and unresolved.returncode!=0 and unresolved_state["failure_class"]=="PUSH_AMBIGUOUS" and changed_first.returncode==70 and changed_reconcile.returncode!=0 and changed_state["failure_class"]=="EVIDENCE_CHANGED" and changed_remote==base)

    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-pushfail"); cli(case,env,"create",str(manifest)); failed=cli(case,env,"approve",f"i{number}-pushfail","--source","operator_agent_explicit_human",check=False,fault="push_failure_before_remote"); retried=cli(case,env,"integrate",f"i{number}-pushfail"); record(results,"H",failed.returncode==70 and retried.returncode==0)

    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-adopt",adoption=True); created=cli(case,env,"create",str(manifest)); adopted=cli(case,env,"approve",f"i{number}-adopt","--source","operator_agent_explicit_human"); record_value=json.loads((pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-adopt.json").read_text()); adoption_receipt=(pathlib.Path(env["GF_APPROVAL_ARTIFACT_ROOT"])/f"i{number}-adopt"/"result.json").is_file(); adoption_clean=git(repo,"status","--short")=="" and record_value.get("cleanup",{}).get("source_worktree_clean") is True; record(results,"J",created.returncode==0 and adopted.returncode==0 and len(record_value["candidate_commits"])==1 and record_value["allowed_files"]==["feature-0.txt"] and adoption_clean)
    case2,repo2,remote2,manifest2,env2,base2=fixture(root,f"i{number}-adopt-future-base",adoption=True); future_manifest=json.loads(manifest2.read_text()); future_manifest.pop("base_sha",None); manifest2.write_text(json.dumps(future_manifest,indent=2)+"\n"); (repo2/"new-base.txt").write_text("GF-010 integrated first\n"); git(repo2,"add","new-base.txt"); git(repo2,"commit","-q","-m","advance trusted base"); git(repo2,"push","-q","origin","main"); future_created=cli(case2,env2,"create",str(manifest2),check=False); future_base_ok=future_created.returncode!=0 and "CANDIDATE_MISMATCH" in future_created.stderr; j_result=results[-1]; j_result["status"]="pass" if j_result["status"]=="pass" and future_base_ok else "fail"; j_result["detail"]=None if j_result["status"]=="pass" else "adoption or incompatible-base rejection failed"
    case3,repo3,remote3,manifest3,env3,base3=fixture(root,f"i{number}-adopt-cleanup-crash",adoption=True,evidence_in_adoption=True); cli(case3,env3,"create",str(manifest3)); cleanup_record_before=json.loads((pathlib.Path(env3["GF_APPROVAL_STATE_ROOT"])/f"i{number}-adopt-cleanup-crash.json").read_text()); preserved_path=pathlib.Path(cleanup_record_before["evidence_snapshots"][0]["validation_snapshot_path"]); cleanup_crash=cli(case3,env3,"approve",f"i{number}-adopt-cleanup-crash","--source","operator_agent_explicit_human",check=False,fault="crash_during_adoption_cleanup"); live_evidence_removed=not (repo3/"evidence-0.json").exists(); cleanup_recovered=cli(case3,env3,"reconcile",f"i{number}-adopt-cleanup-crash"); cleanup_state=json.loads((pathlib.Path(env3["GF_APPROVAL_STATE_ROOT"])/f"i{number}-adopt-cleanup-crash.json").read_text()); adoption_cleanup_recovery=cleanup_crash.returncode==95 and live_evidence_removed and preserved_path.is_file() and cleanup_recovered.returncode==0 and cleanup_state["integration_status"]=="INTEGRATED" and git(repo3,"status","--short")==""; j_result["status"]="pass" if j_result["status"]=="pass" and adoption_cleanup_recovery else "fail"; j_result["detail"]=None if j_result["status"]=="pass" else "adoption content, preserved evidence, future base, or cleanup crash recovery failed"
    cleanup_result=next(entry for entry in results if entry["test"]=="R"); cleanup_result["status"]="pass" if cleanup_result["status"]=="pass" and crash_cleanup and adoption_clean and direct_receipt and crash_receipt and adoption_receipt else "fail"; cleanup_result["detail"]=None if cleanup_result["status"]=="pass" else "normal, crash/adoption cleanup, or final receipt failed"
    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-unrelated",adoption=True); (repo/"unrelated.txt").write_text("no\n"); rejected=cli(case,env,"create",str(manifest),check=False); record(results,"K",rejected.returncode!=0 and (repo/"unrelated.txt").exists())
    case2,repo2,remote2,manifest2,env2,base2=fixture(root,f"i{number}-rename",adoption=True); git(repo2,"mv","base.txt","moved-base.txt"); renamed=cli(case2,env2,"create",str(manifest2),check=False); k_result=results[-1]; rename_ok=renamed.returncode!=0 and "base.txt" in renamed.stderr and "moved-base.txt" in renamed.stderr and (repo2/"moved-base.txt").is_file(); k_result["status"]="pass" if k_result["status"]=="pass" and rename_ok else "fail"; k_result["detail"]=None if k_result["status"]=="pass" else "unrelated file or both sides of staged rename were not rejected/preserved"

    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-bundle",units=3,with_milestone_gates=True); cli(case,env,"create",str(manifest)); bundled=cli(case,env,"approve",f"i{number}-bundle","--source","operator_agent_explicit_human"); state=json.loads((pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-bundle.json").read_text()); checkpoints=[item["name"] for item in state["checkpoints"]]; ordered=all(state["candidate_commits"][index]["parent_sha"]==(state["base_sha"] if index==0 else state["candidate_commits"][index-1]["sha"]) for index in range(3)); milestone_values=[json.loads((pathlib.Path(gate["state_path"])).read_text()) for gate in state["milestone_gates"]]; milestone_cli=[run([str(ROOT/"scripts/gf-milestone.sh"),"--json","status",gate["milestone_id"]],case,env={"GF_MILESTONE_STATE_ROOT":env["GF_MILESTONE_STATE_ROOT"]}) for gate in state["milestone_gates"]]; milestone_ok=all(value["status"]=="complete" and value["human_gate_satisfaction"]["approval_id"]==state["approval_id"] and value["human_gate_satisfaction"]["task_ids"]==[f"UNIT-{index}"] and json.loads(milestone_cli[index].stdout)["status"]=="complete" and json.loads(milestone_cli[index].stdout)["next"]=="MILESTONE_COMPLETE" for index,value in enumerate(milestone_values)); record(results,"L",bundled.returncode==0 and len(state["task_ids"])==3 and len(state["candidate_commits"])==3 and ordered and checkpoints.count("REMOTE_VERIFIED")==1 and len(state["milestone_gate_results"])==3 and milestone_ok and state["integration_status"]=="INTEGRATED")
    case2,repo2,remote2,manifest2,env2,base2=fixture(root,f"i{number}-bundle-gate-crash",units=3,with_milestone_gates=True); cli(case2,env2,"create",str(manifest2)); gate_crash=cli(case2,env2,"approve",f"i{number}-bundle-gate-crash","--source","operator_agent_explicit_human",check=False,fault="crash_during_milestone_gates"); gate_reconcile=cli(case2,env2,"reconcile",f"i{number}-bundle-gate-crash"); gate_state=json.loads((pathlib.Path(env2["GF_APPROVAL_STATE_ROOT"])/f"i{number}-bundle-gate-crash.json").read_text()); gate_histories=[]
    for gate in gate_state["milestone_gates"]:
        history_path=pathlib.Path(gate["state_path"]).parent/"history.jsonl"
        gate_histories.append([json.loads(line) for line in history_path.read_text().splitlines() if line])
    gate_crash_ok=gate_crash.returncode==93 and gate_reconcile.returncode==0 and gate_state["integration_status"]=="INTEGRATED" and all(len([entry for entry in history if entry.get("reason")=="gf010_human_approval_integration"])==1 for history in gate_histories) and [item["name"] for item in gate_state["checkpoints"]].count("REMOTE_VERIFIED")==2
    l_result=results[-1]; l_result["status"]="pass" if l_result["status"]=="pass" and gate_crash_ok else "fail"; l_result["detail"]=None if l_result["status"]=="pass" else "bundle integration, milestone satisfaction, or crash reconciliation failed"
    case3,repo3,remote3,manifest3,env3,base3=fixture(root,f"i{number}-bundle-history-crash",units=1,with_milestone_gates=True); cli(case3,env3,"create",str(manifest3)); history_crash=cli(case3,env3,"approve",f"i{number}-bundle-history-crash","--source","operator_agent_explicit_human",check=False,fault="crash_after_milestone_state_before_history"); history_reconcile=cli(case3,env3,"reconcile",f"i{number}-bundle-history-crash"); history_state=json.loads((pathlib.Path(env3["GF_APPROVAL_STATE_ROOT"])/f"i{number}-bundle-history-crash.json").read_text()); history_gate=history_state["milestone_gates"][0]; history_entries=[json.loads(line) for line in (pathlib.Path(history_gate["state_path"]).parent/"history.jsonl").read_text().splitlines() if line]; history_events=[entry for entry in history_entries if entry.get("reason")=="gf010_human_approval_integration"]; history_crash_ok=history_crash.returncode==92 and history_reconcile.returncode==0 and history_state["integration_status"]=="INTEGRATED" and len(history_events)==1 and history_events[0]["event_id"]==json.loads(pathlib.Path(history_gate["state_path"]).read_text())["human_gate_satisfaction"]["history_event_id"]
    l_result["status"]="pass" if l_result["status"]=="pass" and history_crash_ok else "fail"; l_result["detail"]=None if l_result["status"]=="pass" else "bundle integration, milestone terminal state, or state/history crash reconciliation failed"

    multi=root/f"i{number}-multi"; multi.mkdir(); shared_state=multi/"state"; shared_art=multi/"art"
    for suffix in ["one","two"]:
        case,repo,remote,manifest,env,base=fixture(multi,suffix); env={**env,"GF_APPROVAL_STATE_ROOT":str(shared_state),"GF_APPROVAL_ARTIFACT_ROOT":str(shared_art)}; value=json.loads(manifest.read_text()); value["approval_id"]=suffix; manifest.write_text(json.dumps(value)); cli(case,env,"create",str(manifest))
    ambiguous=cli(multi,{"GF_APPROVAL_STATE_ROOT":str(shared_state),"GF_APPROVAL_ARTIFACT_ROOT":str(shared_art)},"approve","--current","--source","operator_agent_explicit_human",check=False); record(results,"M",ambiguous.returncode!=0 and "MULTIPLE_PENDING" in ambiguous.stderr)

    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-concurrent"); cli(case,env,"create",str(manifest)); command=[str(CLI),"approve",f"i{number}-concurrent","--source","operator_agent_explicit_human"]; first_env={**os.environ,**env,"GF_GF010_ENABLE_TEST_HOOKS":"1","GF_GF010_HOLD_LOCK_MS":"250"}; second_env={**os.environ,**env}; first=subprocess.Popen(command,cwd=case,env=first_env,text=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE); time.sleep(0.05); second=run(command,case,env=second_env,check=False); revoke_race=run([str(CLI),"revoke",f"i{number}-concurrent"],case,env=second_env,check=False); first_out,first_err=first.communicate(); concurrent_state=json.loads((pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-concurrent.json").read_text()); target_head=git(repo,"ls-remote","origin","refs/heads/main").split()[0]; concurrency_ok=first.returncode==0 and second.returncode==70 and "TRANSACTION_BUSY" in second.stderr and revoke_race.returncode==70 and "TRANSACTION_BUSY" in revoke_race.stderr and concurrent_state["integration_status"]=="INTEGRATED" and target_head==concurrent_state["integration_commit"] and [item["name"] for item in concurrent_state["checkpoints"]].count("PUSH_STARTED")==1
    results[-1]["status"]="pass" if results[-1]["status"]=="pass" and concurrency_ok else "fail"; results[-1]["detail"]=None if results[-1]["status"]=="pass" else "pending-selection or concurrent-lock invariant failed"

    for letter,external in [("O",False),("P",True)]:
        case,repo,remote,manifest,env,base=fixture(root,f"i{number}-pr-{letter}",mode="pull_request",external=external); cli(case,env,"create",str(manifest)); pr=cli(case,env,"approve",f"i{number}-pr-{letter}","--source","operator_agent_explicit_human",check=False); state=json.loads((pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-pr-{letter}.json").read_text()); checkpoints=[item["name"] for item in state["checkpoints"]]; branch_exists=bool(git(repo,"ls-remote","--heads","origin",f"refs/heads/gf-approval/i{number}-pr-{letter}",check=False)); pr_receipt=pathlib.Path(env["GF_APPROVAL_ARTIFACT_ROOT"])/f"i{number}-pr-{letter}"/"pr.json"; record(results,letter,(pr.returncode==0 and state["integration_status"]=="INTEGRATED" and state["pr_number"] and state["required_checks_status"]=="pass" and "PR_CREATED" in checkpoints and "PR_MERGED" in checkpoints and state["remote_head_after"]==state["merge_commit"] and not branch_exists and pr_receipt.is_file()) if not external else (pr.returncode!=0 and state["failure_class"]=="HUMAN_REQUIRED_EXTERNAL_POLICY" and state["pr_number"] and branch_exists and git(repo,"ls-remote","origin","refs/heads/main").split()[0]==base))
    other=case/"review-wait-advance"; run(["git","clone","-q",str(remote),str(other)],case); git(other,"checkout","-q","-b","main","origin/main"); git(other,"config","user.name","Remote"); git(other,"config","user.email","remote@test"); (other/"while-reviewing.txt").write_text("target advanced during review\n"); git(other,"add","."); git(other,"commit","-q","-m","advance while reviewing"); git(other,"push","-q","origin","main")
    reviewed=cli(case,env,"reconcile",f"i{number}-pr-P",extra_env={"GF_GF010_ENABLE_TEST_HOOKS":"1","GF_GF010_EXTERNAL_REVIEW_APPROVED":"1"}); reviewed_state=json.loads((pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-pr-P.json").read_text()); reviewed_checks=[item["name"] for item in reviewed_state["checkpoints"]]; p_result=next(entry for entry in results if entry["test"]=="P"); review_resume_ok=reviewed.returncode==0 and reviewed_state["integration_status"]=="INTEGRATED" and reviewed_state["remote_head_after"]==reviewed_state["merge_commit"] and "PR_TARGET_REFRESHED" in reviewed_checks and "PR_REVALIDATED" in reviewed_checks and reviewed_checks.count("REQUIRED_CHECKS_PASS")==1; p_result["status"]="pass" if p_result["status"]=="pass" and review_resume_ok else "fail"; p_result["detail"]=None if p_result["status"]=="pass" else "external-review stop, final-base refresh/revalidation, or automatic resume failed"
    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-pr-reset",mode="pull_request",external=True); cli(case,env,"create",str(manifest)); other=case/"initial-pr-base"; run(["git","clone","-q",str(remote),str(other)],case); git(other,"checkout","-q","-b","main","origin/main"); git(other,"config","user.name","Remote"); git(other,"config","user.email","remote@test"); (other/"base-b.txt").write_text("base B\n"); git(other,"add","."); git(other,"commit","-q","-m","base B"); git(other,"push","-q","origin","main"); waiting=cli(case,env,"approve",f"i{number}-pr-reset","--source","operator_agent_explicit_human",check=False); git(repo,"push","-q","--force","origin",f"{base}:refs/heads/main"); reset_review=cli(case,env,"reconcile",f"i{number}-pr-reset",check=False,extra_env={"GF_GF010_ENABLE_TEST_HOOKS":"1","GF_GF010_EXTERNAL_REVIEW_APPROVED":"1"}); reset_review_state=json.loads((pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-pr-reset.json").read_text()); pr_reset_ok=waiting.returncode!=0 and reset_review.returncode!=0 and reset_review_state["failure_class"]=="REMOTE_REWRITTEN_BEFORE_PR_MERGE" and git(repo,"ls-remote","origin","refs/heads/main").split()[0]==base; p_result["status"]="pass" if p_result["status"]=="pass" and pr_reset_ok else "fail"; p_result["detail"]=None if p_result["status"]=="pass" else "PR descendant refresh or non-descendant reset rejection failed"
    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-pr-recovery",mode="pull_request",external=False); cli(case,env,"create",str(manifest)); pr_crash=cli(case,env,"approve",f"i{number}-pr-recovery","--source","operator_agent_explicit_human",check=False,fault="crash_after_pr_created"); recovered=cli(case,env,"reconcile",f"i{number}-pr-recovery"); recovery_state=json.loads((pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-pr-recovery.json").read_text()); recovery_checkpoints=[item["name"] for item in recovery_state["checkpoints"]]; o_result=next(entry for entry in results if entry["test"]=="O"); pr_recovery_ok=pr_crash.returncode==98 and recovered.returncode==0 and recovery_state["integration_status"]=="INTEGRATED" and recovery_checkpoints.count("PR_CREATED")==1 and recovery_checkpoints.count("PR_MERGED")==1 and recovery_state.get("cleanup",{}).get("temporary_worktree_removed") is True; o_result["status"]="pass" if o_result["status"]=="pass" and pr_recovery_ok else "fail"; o_result["detail"]=None if o_result["status"]=="pass" else "PR policy or exactly-once recovery failed"
    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-pr-merge-recovery",mode="pull_request",external=False); cli(case,env,"create",str(manifest)); merge_crash=cli(case,env,"approve",f"i{number}-pr-merge-recovery","--source","operator_agent_explicit_human",check=False,fault="crash_after_pr_merge"); merge_recovered=cli(case,env,"reconcile",f"i{number}-pr-merge-recovery"); merge_state=json.loads((pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-pr-merge-recovery.json").read_text()); merge_checks=[item["name"] for item in merge_state["checkpoints"]]; merge_recovery_ok=merge_crash.returncode==99 and merge_recovered.returncode==0 and merge_state["integration_status"]=="INTEGRATED" and merge_checks.count("PR_MERGE_STARTED")==1 and merge_checks.count("REMOTE_VERIFIED")==1 and merge_state.get("cleanup",{}).get("temporary_worktree_removed") is True; o_result["status"]="pass" if o_result["status"]=="pass" and merge_recovery_ok else "fail"; o_result["detail"]=None if o_result["status"]=="pass" else "PR create/merge exactly-once recovery failed"
    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-pr-merge-unknown",mode="pull_request",external=False); cli(case,env,"create",str(manifest)); unknown_crash=cli(case,env,"approve",f"i{number}-pr-merge-unknown","--source","operator_agent_explicit_human",check=False,fault="crash_after_pr_merge_unknown"); unknown_recovered=cli(case,env,"reconcile",f"i{number}-pr-merge-unknown"); unknown_state=json.loads((pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-pr-merge-unknown.json").read_text()); unknown_checks=[item["name"] for item in unknown_state["checkpoints"]]; unknown_ok=unknown_crash.returncode==100 and unknown_recovered.returncode==0 and unknown_state["integration_status"]=="INTEGRATED" and unknown_state["merge_commit"]!=unknown_state["integration_commit"] and unknown_checks.count("PR_MERGE_RECONCILED")==1 and unknown_checks.count("PR_MERGE_STARTED")==1; o_result["status"]="pass" if o_result["status"]=="pass" and unknown_ok else "fail"; o_result["detail"]=None if o_result["status"]=="pass" else "unknown real-merge result was not reconciled before generic push logic"
    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-github-retarget",mode="pull_request",adapter="github"); cli(case,env,"create",str(manifest)); retarget_state_path=pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-github-retarget.json"; retarget_state=json.loads(retarget_state_path.read_text()); retarget_state["pr_number"]=123; retarget_state_path.write_text(json.dumps(retarget_state,indent=2)+"\n"); fake_bin=case/"bin"; fake_bin.mkdir(); merge_marker=case/"merge-called"; fake_gh=fake_bin/"gh"; fake_gh.write_text("#!/usr/bin/env bash\nif [[ \" $* \" == *\" pr merge \"* ]]; then touch \"$GF_TEST_MERGE_MARKER\"; exit 0; fi\nhead=$(jq -r '.integration_commit' \"$GF_APPROVAL_STATE_ROOT/$GF_TEST_APPROVAL_ID.json\")\njq -cn --arg head \"$head\" '{state:\"OPEN\",headRefOid:$head,baseRefName:\"wrong-target\",mergeCommit:null,reviewDecision:\"\"}'\n"); fake_gh.chmod(0o755); retargeted=cli(case,env,"approve",f"i{number}-github-retarget","--source","operator_agent_explicit_human",check=False,extra_env={"PATH":str(fake_bin)+os.pathsep+os.environ["PATH"],"GF_TEST_MERGE_MARKER":str(merge_marker),"GF_TEST_APPROVAL_ID":f"i{number}-github-retarget"}); retarget_after=json.loads(retarget_state_path.read_text()); retarget_safe=retargeted.returncode!=0 and retarget_after["failure_class"]=="PR_IDENTITY_CHANGED" and not merge_marker.exists() and git(repo,"ls-remote","origin","refs/heads/main").split()[0]==base; o_result["status"]="pass" if o_result["status"]=="pass" and retarget_safe else "fail"; o_result["detail"]=None if o_result["status"]=="pass" else "GitHub PR head/base identity was not proven before mutation"
    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-pr-branch-moved",mode="pull_request",external=False); cli(case,env,"create",str(manifest)); moved_crash=cli(case,env,"approve",f"i{number}-pr-branch-moved","--source","operator_agent_explicit_human",check=False,fault="crash_after_pr_merge"); moved_state_path=pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-pr-branch-moved.json"; moved_before=json.loads(moved_state_path.read_text()); moved_branch=moved_before["pr_branch"]; attacker=case/"branch-attacker"; run(["git","clone","-q",str(remote),str(attacker)],case); git(attacker,"checkout","-q","-b","attacker",f"origin/{moved_branch}"); git(attacker,"config","user.name","Remote"); git(attacker,"config","user.email","remote@test"); (attacker/"unexpected-pr-work.txt").write_text("must survive cleanup\n"); git(attacker,"add","."); git(attacker,"commit","-q","-m","unexpected PR branch work"); attacker_head=git(attacker,"rev-parse","HEAD"); git(attacker,"push","-q","origin",f"HEAD:refs/heads/{moved_branch}"); moved_reconcile=cli(case,env,"reconcile",f"i{number}-pr-branch-moved",check=False); moved_after=json.loads(moved_state_path.read_text()); moved_remote=git(repo,"ls-remote","origin",f"refs/heads/{moved_branch}").split()[0]; moved_safe=moved_crash.returncode==99 and moved_reconcile.returncode!=0 and moved_after["failure_class"]=="PR_BRANCH_MOVED" and moved_remote==attacker_head and moved_after["integration_status"]=="HUMAN_REQUIRED"
    case2,repo2,remote2,manifest2,env2,base2=fixture(root,f"i{number}-pr-delete-rejected",mode="pull_request",external=False); cli(case2,env2,"create",str(manifest2)); delete_crash=cli(case2,env2,"approve",f"i{number}-pr-delete-rejected","--source","operator_agent_explicit_human",check=False,fault="crash_after_pr_merge"); delete_state_path=pathlib.Path(env2["GF_APPROVAL_STATE_ROOT"])/f"i{number}-pr-delete-rejected.json"; delete_before=json.loads(delete_state_path.read_text()); hook=remote2/"hooks"/"update"; hook.write_text("#!/usr/bin/env bash\nexit 1\n"); hook.chmod(0o755); delete_reconcile=cli(case2,env2,"reconcile",f"i{number}-pr-delete-rejected",check=False); delete_after=json.loads(delete_state_path.read_text()); delete_branch_present=bool(git(repo2,"ls-remote","origin",f"refs/heads/{delete_before['pr_branch']}",check=False)); deletion_safe=delete_crash.returncode==99 and delete_reconcile.returncode!=0 and delete_after["failure_class"]=="PR_BRANCH_CLEANUP_AMBIGUOUS" and delete_branch_present and delete_after["integration_status"]=="HUMAN_REQUIRED"
    case3,repo3,remote3,manifest3,env3,base3=fixture(root,f"i{number}-pr-branch-race",mode="pull_request",external=False); cli(case3,env3,"create",str(manifest3)); race_crash=cli(case3,env3,"approve",f"i{number}-pr-branch-race","--source","operator_agent_explicit_human",check=False,fault="crash_after_pr_merge"); race_state_path=pathlib.Path(env3["GF_APPROVAL_STATE_ROOT"])/f"i{number}-pr-branch-race.json"; race_before=json.loads(race_state_path.read_text()); race_branch=race_before["pr_branch"]; attacker=case3/"race-attacker"; run(["git","clone","-q",str(remote3),str(attacker)],case3); git(attacker,"checkout","-q","-b","attacker",f"origin/{race_branch}"); git(attacker,"config","user.name","Remote"); git(attacker,"config","user.email","remote@test"); (attacker/"raced-work.txt").write_text("must survive compare-and-delete\n"); git(attacker,"add","."); git(attacker,"commit","-q","-m","race cleanup"); race_head=git(attacker,"rev-parse","HEAD"); git(attacker,"push","-q","origin",f"HEAD:refs/heads/race-staged"); real_git=shutil.which("git"); race_bin=case3/"race-bin"; race_bin.mkdir(); git_wrapper=race_bin/"git"; git_wrapper.write_text("#!/usr/bin/env bash\nif [[ \" $* \" == *\" push --force-with-lease=\"* ]]; then \"$GF_TEST_REAL_GIT\" --git-dir=\"$GF_TEST_REMOTE\" update-ref \"$GF_TEST_BRANCH_REF\" \"$GF_TEST_RACE_HEAD\"; fi\nexec \"$GF_TEST_REAL_GIT\" \"$@\"\n"); git_wrapper.chmod(0o755); race_reconcile=cli(case3,env3,"reconcile",f"i{number}-pr-branch-race",check=False,extra_env={"PATH":str(race_bin)+os.pathsep+os.environ["PATH"],"GF_TEST_REAL_GIT":real_git,"GF_TEST_REMOTE":str(remote3),"GF_TEST_BRANCH_REF":f"refs/heads/{race_branch}","GF_TEST_RACE_HEAD":race_head}); race_after=json.loads(race_state_path.read_text()); race_remote=git(repo3,"ls-remote","origin",f"refs/heads/{race_branch}").split()[0]; race_safe=race_crash.returncode==99 and race_reconcile.returncode!=0 and race_after["failure_class"]=="PR_BRANCH_CLEANUP_AMBIGUOUS" and race_remote==race_head and race_after["integration_status"]=="HUMAN_REQUIRED"
    o_result["status"]="pass" if o_result["status"]=="pass" and moved_safe and deletion_safe and race_safe else "fail"; o_result["detail"]=None if o_result["status"]=="pass" else "PR integration, recovery, or compare-and-delete temporary-branch cleanup failed"

    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-validation"); cli(case,env,"create",str(manifest)); bad=cli(case,env,"approve",f"i{number}-validation","--source","operator_agent_explicit_human",check=False,fault="validation_failure"); remote_head=git(repo,"ls-remote","origin","refs/heads/main").split()[0]
    case2,repo2,remote2,manifest2,env2,base2=fixture(root,f"i{number}-validation-dirty"); cli(case2,env2,"create",str(manifest2)); dirty_validator=cli(case2,env2,"approve",f"i{number}-validation-dirty","--source","operator_agent_explicit_human",check=False,fault="validation_dirty_worktree"); dirty_state=json.loads((pathlib.Path(env2["GF_APPROVAL_STATE_ROOT"])/f"i{number}-validation-dirty.json").read_text()); dirty_remote=git(repo2,"ls-remote","origin","refs/heads/main").split()[0]; record(results,"Q",bad.returncode!=0 and remote_head==base and dirty_validator.returncode!=0 and dirty_state["failure_class"]=="INTEGRATION_VALIDATION_SCOPE_FAILED" and dirty_remote==base2)
    case3,repo3,remote3,manifest3,env3,base3=fixture(root,f"i{number}-validation-shared-deps",shared_dependencies=True); cli(case3,env3,"create",str(manifest3)); shared=cli(case3,env3,"approve",f"i{number}-validation-shared-deps","--source","operator_agent_explicit_human"); shared_state=json.loads((pathlib.Path(env3["GF_APPROVAL_STATE_ROOT"])/f"i{number}-validation-shared-deps.json").read_text()); shared_validation=json.loads((pathlib.Path(env3["GF_APPROVAL_ARTIFACT_ROOT"])/f"i{number}-validation-shared-deps"/"validation.json").read_text()); shared_ok=shared.returncode==0 and shared_state["integration_status"]=="INTEGRATED" and shared_validation["dependency"]["mode"]=="shared_locked_node_modules" and (repo3/"node_modules/fake-tool.txt").is_file() and git(repo3,"status","--short")==""; q_result=results[-1]; q_result["status"]="pass" if q_result["status"]=="pass" and shared_ok else "fail"; q_result["detail"]=None if q_result["status"]=="pass" else "validation failure, dirty-tree, or shared locked dependency behavior failed"
    case4,repo4,remote4,manifest4,env4,base4=fixture(root,f"i{number}-validation-deps-mismatch",shared_dependencies=True); cli(case4,env4,"create",str(manifest4)); (repo4/"package-lock.json").write_text('{"name":"changed-after-approval","lockfileVersion":3}\n'); mismatch=cli(case4,env4,"approve",f"i{number}-validation-deps-mismatch","--source","operator_agent_explicit_human",check=False); mismatch_state=json.loads((pathlib.Path(env4["GF_APPROVAL_STATE_ROOT"])/f"i{number}-validation-deps-mismatch.json").read_text()); mismatch_ok=mismatch.returncode!=0 and mismatch_state["failure_class"]=="INTEGRATION_VALIDATION_DEPENDENCY_INVALID" and git(repo4,"ls-remote","origin","refs/heads/main").split()[0]==base4; q_result["status"]="pass" if q_result["status"]=="pass" and mismatch_ok else "fail"; q_result["detail"]=None if q_result["status"]=="pass" else "validation failure, dirty-tree, shared dependency, or lock mismatch behavior failed"
    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-scheduler"); cli(case,env,"create",str(manifest)); scheduled=cli(case,{**env,"GF_UNATTENDED_RUN":"1"},"approve",f"i{number}-scheduler","--source","operator_agent_explicit_human",check=False); runner_root=case/"runner-probe"; (runner_root/"scripts").mkdir(parents=True); copied_runner=runner_root/"scripts/gf-unattended-run.sh"; shutil.copy2(ROOT/"scripts/gf-unattended-run.sh",copied_runner); fake_milestone=runner_root/"scripts/gf-milestone.sh"; fake_milestone.write_text("#!/usr/bin/env bash\n\"$GF_TEST_APPROVAL_CLI\" approve \"$GF_TEST_APPROVAL_ID\" --source operator_agent_explicit_human >\"$GF_TEST_PROBE_STDOUT\" 2>\"$GF_TEST_PROBE_STDERR\"\nprintf '%s\\n' \"$?\" >\"$GF_TEST_PROBE_CODE\"\nprintf '%s\\n' '{\"status\":\"pending_human\",\"tasks\":{},\"next\":\"MILESTONE_COMPLETE\"}'\n"); fake_milestone.chmod(0o755); runner_state=case/"runner-milestones"/"GF-SCHEDULER-PROBE"; runner_state.mkdir(parents=True); (runner_state/"state.json").write_text('{"status":"pending_human","tasks":{}}\n'); probe_stdout=runner_root/"approval.stdout"; probe_stderr=runner_root/"approval.stderr"; probe_code=runner_root/"approval.code"; runner_env={**env,"GF_MILESTONE_STATE_ROOT":str(case/"runner-milestones"),"GF_UNATTENDED_ARTIFACT_ROOT":str(case/"runner-artifacts"),"GF_TEST_APPROVAL_CLI":str(CLI),"GF_TEST_APPROVAL_ID":f"i{number}-scheduler","GF_TEST_PROBE_STDOUT":str(probe_stdout),"GF_TEST_PROBE_STDERR":str(probe_stderr),"GF_TEST_PROBE_CODE":str(probe_code)}; canonical=run([str(copied_runner),"--json","--max-tasks","1","--max-minutes","1","GF-SCHEDULER-PROBE"],case,env=runner_env,check=False); scheduler_state=json.loads((pathlib.Path(env["GF_APPROVAL_STATE_ROOT"])/f"i{number}-scheduler.json").read_text()); canonical_blocked=canonical.returncode==0 and probe_code.read_text().strip()=="20" and "SCHEDULER_APPROVAL_FORBIDDEN" in probe_stderr.read_text() and scheduler_state["integration_status"]=="PENDING_HUMAN"; record(results,"S",scheduled.returncode!=0 and "SCHEDULER_APPROVAL_FORBIDDEN" in scheduled.stderr and canonical_blocked)
    case,repo,remote,manifest,env,base=fixture(root,f"i{number}-force"); value=json.loads(manifest.read_text()); value["integration"]["allow_force_push"]=True; manifest.write_text(json.dumps(value)); force=cli(case,env,"create",str(manifest),check=False)
    case2,repo2,remote2,manifest2,env2,base2=fixture(root,f"i{number}-redirect"); value=json.loads(manifest2.read_text()); value["target_branch"]="unauthorized"; manifest2.write_text(json.dumps(value)); redirect=cli(case2,env2,"create",str(manifest2),check=False); record(results,"T",force.returncode!=0 and "FORCE_PUSH_FORBIDDEN" in force.stderr and redirect.returncode!=0 and "INTEGRATION_POLICY_MISMATCH" in redirect.stderr)
    case3,repo3,remote3,manifest3,env3,base3=fixture(root,f"i{number}-remote-swap"); cli(case3,env3,"create",str(manifest3)); attacker=case3/"attacker.git"; run(["git","init","--bare","-q",str(attacker)],case3); git(repo3,"remote","set-url","--push","origin",str(attacker)); swapped=cli(case3,env3,"approve",f"i{number}-remote-swap","--source","operator_agent_explicit_human",check=False); t_result=results[-1]; remote_identity_ok=swapped.returncode!=0 and "REMOTE_IDENTITY_CHANGED" in swapped.stderr and not git(repo3,"ls-remote",str(attacker),"refs/heads/main",check=False); t_result["status"]="pass" if t_result["status"]=="pass" and remote_identity_ok else "fail"; t_result["detail"]=None if t_result["status"]=="pass" else "force, target-redirection, or remote-identity rejection failed"
    identity_suite=run([str(ROOT/"scripts/gf-identity-acceptance.sh")],root,check=False); record(results,"U",identity_suite.returncode==0,identity_suite.stderr.strip() or identity_suite.stdout.strip() if identity_suite.returncode else None)
    if evidence_root is not None:
        evidence_root.mkdir(parents=True, exist_ok=True)
        selected=[f"i{number}-direct",f"i{number}-reset-before-push",f"i{number}-conflict",f"i{number}-crash",f"i{number}-crash-evidence-missing",f"i{number}-crash-prepush",f"i{number}-crash-worktree-gap",f"i{number}-crash-advanced",f"i{number}-crash-rewritten",f"i{number}-ambiguous-arrived",f"i{number}-ambiguous-absent",f"i{number}-ambiguous-unresolved",f"i{number}-ambiguous-evidence-changed",f"i{number}-adopt",f"i{number}-adopt-future-base",f"i{number}-adopt-cleanup-crash",f"i{number}-unrelated",f"i{number}-rename",f"i{number}-bundle",f"i{number}-bundle-gate-crash",f"i{number}-bundle-history-crash",f"i{number}-concurrent",f"i{number}-pr-O",f"i{number}-pr-P",f"i{number}-pr-reset",f"i{number}-pr-recovery",f"i{number}-pr-merge-recovery",f"i{number}-pr-merge-unknown",f"i{number}-github-retarget",f"i{number}-pr-branch-moved",f"i{number}-pr-delete-rejected",f"i{number}-pr-branch-race",f"i{number}-validation",f"i{number}-validation-dirty",f"i{number}-validation-shared-deps",f"i{number}-validation-deps-mismatch",f"i{number}-scheduler",f"i{number}-force",f"i{number}-multi"]
        for name in selected:
            source=root/name
            if not source.exists(): continue
            destination=evidence_root/name
            destination.mkdir(parents=True,exist_ok=True)
            for filename in ["manifest.json","integration-policy.json"]:
                if (source/filename).is_file(): shutil.copy2(source/filename,destination/filename)
            for dirname in ["state","artifacts","art","milestones","runner-probe"]:
                if (source/dirname).is_dir(): shutil.copytree(source/dirname,destination/dirname,dirs_exist_ok=True)
            if (source/"repo").is_dir():
                (destination/"repo-status.txt").write_text(git(source/"repo","status","--short")+"\n")
                (destination/"remote-main.txt").write_text(git(source/"repo","ls-remote","origin","refs/heads/main")+"\n")
    return results

def main():
    parser=argparse.ArgumentParser(); parser.add_argument("--iterations",type=int,default=1); parser.add_argument("--artifact-root",type=pathlib.Path,default=ROOT/"artifacts/gf-010"/f"gf010-{int(time.time())}"); args=parser.parse_args()
    args.artifact_root.mkdir(parents=True,exist_ok=True); started=time.time(); all_results=[]
    with tempfile.TemporaryDirectory(prefix="gf010-acceptance-") as temp:
        temp_root=pathlib.Path(temp)
        for number in range(1,args.iterations+1):
            results=iteration(temp_root,number,args.artifact_root/"fixtures" if number==1 else None); all_results.extend({"iteration":number,**entry} for entry in results)
            failures=sum(1 for entry in results if entry["status"]!="pass"); print(f"iteration {number:02d}: {21-failures}/21 PASS")
    failed=[entry for entry in all_results if entry["status"]!="pass"]
    result={"slice":"GF-010","status":"pass" if not failed else "fail","iterations":args.iterations,"checks_per_iteration":21,"checks":all_results,"failures":len(failed),"duration_seconds":round(time.time()-started,6),"real_github_smoke":"not_run"}
    (args.artifact_root/"results.jsonl").write_text("".join(json.dumps(entry,sort_keys=True)+"\n" for entry in all_results),encoding="utf-8")
    (args.artifact_root/"result.json").write_text(json.dumps(result,indent=2)+"\n"); print(f"GF-010 ACCEPTANCE: {result['status'].upper()}\nFAILURES: {len(failed)}\nEVIDENCE: {args.artifact_root}")
    return 0 if not failed else 1
if __name__=="__main__": raise SystemExit(main())
